apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: trustee-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: "Trustee Operator Catalog"
  sourceType: grpc
  image: "quay.io/redhat-user-workloads/ose-osc-tenant/trustee-test-fbc:1.0.0-1763473348"
  updateStrategy:
    registryPoll:
      interval: 5m
