{{- if .Values.trusteeConfig.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.trusteeConfig.name }}-crd-wait
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: trustee-operator-crd-wait
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backoffLimit: 10
  template:
    metadata:
      name: {{ .Values.trusteeConfig.name }}-crd-wait
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.crdWaitJob.serviceAccountName | default "default" }}
      containers:
      - name: wait-for-crd
        image: {{ .Values.crdWaitJob.image | default "quay.io/openshift/origin-cli:latest" }}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Waiting for TrusteeConfig CRD to be available..."

          # Determine which CLI tool to use (oc or kubectl)
          if command -v oc &> /dev/null; then
            CLI="oc"
          elif command -v kubectl &> /dev/null; then
            CLI="kubectl"
          else
            echo "ERROR: Neither oc nor kubectl found in container"
            echo "Container image must have either oc or kubectl installed"
            exit 1
          fi

          echo "Using CLI tool: $CLI"

          MAX_ATTEMPTS=60
          SLEEP_INTERVAL=5
          attempt=0

          while [ $attempt -lt $MAX_ATTEMPTS ]; do
            if $CLI get crd trusteeconfigs.confidentialcontainers.org >/dev/null 2>&1; then
              echo "TrusteeConfig CRD is now available!"
              exit 0
            fi

            attempt=$((attempt + 1))
            echo "Attempt $attempt/$MAX_ATTEMPTS: CRD not yet available, waiting ${SLEEP_INTERVAL}s..."
            sleep $SLEEP_INTERVAL
          done

          echo "ERROR: TrusteeConfig CRD did not become available after $((MAX_ATTEMPTS * SLEEP_INTERVAL)) seconds"
          echo "Check the operator installation status with: oc get csv -n {{ .Values.namespace.name }}"
          exit 1
{{- end }}
