{{- if .Values.operatorGroup.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorGroup.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  targetNamespaces:
  - {{ .Values.namespace.name }}
{{- end }}
